=== sergey-fedorov/cucumber-api-tests-poc/src/test/resources/__files/pet_schema.json
{
  "$id": "https://petstore.swagger.io/v2/pet.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": ["name", "photoUrls"],
  "properties": {
    "id": {
      "type": "integer",
      "format": "int64"
    },
    "category": {
      "$ref": "#/Category"
    },
    "name": {
      "type": "string",
      "example": "doggie"
    },
    "photoUrls": {
      "type": "array",
      "xml": {
        "wrapped": true
      },
      "items": {
        "type": "string",
        "xml": {
          "name": "photoUrl"
        }
      }
    },
    "tags": {
      "type": "array",
      "xml": {
        "wrapped": true
      },
      "items": {
        "xml": {
          "name": "tag"
        },
        "$ref": "#/Tag"
      }
    },
    "status": {
      "type": "string",
      "description": "pet status in the store",
      "enum": ["available", "pending", "sold"]
    }
  },
  "xml": {
    "name": "Pet"
  },
  "Tag": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "format": "int64"
      },
      "name": {
        "type": "string"
      }
    },
    "xml": {
      "name": "Tag"
    }
  },
  "Category": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "format": "int64"
      },
      "name": {
        "type": "string"
      }
    },
    "xml": {
      "name": "Category"
    }
  }
}

=== sergey-fedorov/cucumber-api-tests-poc/src/test/resources/__files/get_pet_list.json
[
  {
    "id": 1,
    "category": {
      "id": 1,
      "name": "CatOne"
    },
    "name": "anyNameOne",
    "photoUrls": [
      "https://example.com/buddyOne.jpg"
    ],
    "tags": [
      {
        "id": 1,
        "name": "TagOne"
      }
    ],
    "status": "available"
  },
  {
    "id": 2,
    "category": {
      "id": 2,
      "name": "CatTwo"
    },
    "name": "anyNameTwo",
    "photoUrls": [
      "https://example.com/buddyTwo.jpg"
    ],
    "tags": [
      {
        "id": 2,
        "name": "TagTwo"
      }
    ],
    "status": "sold"
  },
  {
    "id": 3,
    "category": {
      "id": 1,
      "name": "CatOne"
    },
    "name": "anyNameThree",
    "photoUrls": [
      "https://example.com/buddyThree.jpg"
    ],
    "tags": [
      {
        "id": 2,
        "name": "TagTwo"
      }
    ],
    "status": "sold"
  },
  {
    "id": 4,
    "category": {
      "id": 2,
      "name": "CatTwo"
    },
    "name": "anyNameFour",
    "photoUrls": [
      "https://example.com/buddyFour1.jpg",
      "https://example.com/buddyFour2.jpg"
    ],
    "tags": [
      {
        "id": 2,
        "name": "TagTwo"
      }
    ],
    "status": "sold"
  },
  {
    "id": 5,
    "category": {
      "id": 2,
      "name": "CatTwo"
    },
    "name": "anyNameFive",
    "photoUrls": [
      "https://example.com/buddyFive.jpg"
    ],
    "tags": [
      {
        "id": 1,
        "name": "TagOne"
      }
    ],
    "status": "available"
  }
]
